# 地圖邊界與禁區配置 (多邊形頂點)
# map_config:
#   # 搜尋範圍區域 (不規則多邊形)
#   search_boundary:
#     points:
#       - [-10.5, -5.0]
#       - [6.5, -5.0]
#       - [6.5, 2.0]
#       - [-10.5, 2.0]
# map_config:
#   # 搜尋範圍區域 (不規則多邊形)
#   search_boundary:
#     points:
#       - [0.0, 0.0]
#       - [-1.5976, 5.6124]
#       - [-3.1136, 10.6116]
#       - [-4.282, 15.9647]
#       - [-5.7466, 21.3838]
#       - [-3.2792, 26.1297]
#       - [-7.8313, 23.0469]
#       - [-8.8681, 31.0482]
#       - [-3.6201, 32.1155]
#       - [1.7414, 30.1733]
#       - [7.4758, 28.6367]
#       - [9.4474, 23.9564]
#       - [7.9475, 18.4338]
#       - [6.2018, 13.6637]
#       - [3.5058, 8.847]
#       - [1.4822, 3.84]
# map_config:
#   # 搜尋範圍區域 (不規則多邊形)
#   search_boundary:
#     points:
#       - [0.0, 0.0]
#       - [-1.6378, -4.8993]
#       - [3.1994, -6.5259]
#       - [8.375, -6.0598]
#       - [10.0365, -0.9889]
#       - [12.9742, 3.6966]
#       - [8.4387, 1.5308]
#       - [3.9035, -0.5916]
#上面是中壢

#test紅樓
map_config:
  # 搜尋範圍區域 (不規則多邊形)
  search_boundary:
    points:
      - [0.0, 0.0]
      - [-1.3447, 0.0]
      - [-3.1937, 0.1852]
      - [-4.2022, 0.1852]
      - [-5.2108, 0.3704]
      - [-7.0598, 0.3704]
      - [-8.5726, 0.3704]
      - [-9.413, -0.1852]
      - [-9.413, -1.667]
      - [-9.413, -3.5192]
      - [-9.5811, -4.6305]
      - [-8.7407, -5.1862]
      - [-7.2278, -5.1862]
      - [-5.547, -5.1862]
      - [-3.8661, -5.0009]
      - [-2.6894, -4.8157]
      - [-1.3447, -4.8157]
      - [-0.6724, -4.0748]
      - [-0.5043, -2.9635]


  # 禁區列表
  # forbidden_zones:
  #   - name: "center_pool"
  #     points:
  #       - [-1.0, -1.0]
  #       - [1.0, -1.0]
  #       - [1.0, 1.0]
  #       - [-1.0, 1.0]
    # - name: "irregular_stone"
    #   points:
    #     - [4.0, 4.0]
    #     - [6.0, 4.0]
    #     - [5.0, 6.0]